name: 'Repo Ops'
description: 'Action to execute gh repo commands like archive, unarchive, create, etc.'
author: 'rmottanet'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  action:
    description: 'The gh repo action to execute (e.g., archive, unarchive, create)'
    required: true
  owner:
    description: 'The repository owner (user or org)'
    required: true
  repo_name:
    description: 'The repository name'
    required: true
  description:
    description: 'The repository description (optional, used with "create" action)'
    required: false
  visibility:
    description: 'The repository visibility (public, private or internal, default is "public" for "create" action)'
    required: false
    default: 'public'
  team:
    description: 'The team to grant access to the new repository. (Used with "create" action)'
    required: false
  add_readme:
    description: 'Set to "true" to initialize the new repository with a README. (Used with "create" action)'
    required: false
    default: 'false'
  template:
    description: 'The repository to use as a template. Cannot be used with add_readme or team inputs. (Used with "create" action)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run repo-action.sh
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/repo-action.sh
        ${{ github.action_path }}/repo-action.sh \
          "${{ inputs.action }}" \
          "${{ inputs.owner }}" \
          "${{ inputs.repo_name }}" \
          "${{ inputs.description }}" \
          "${{ inputs.visibility }}" \
          "${{ inputs.team }}" \
          "${{ inputs.add_readme }}" \
          "${{ inputs.template }}"
